### ISSUE TITLE
ETH Sofia - Events bölümüne eklenmesi

### ISSUE THREAD

**Issue by gergineth** [node101-io/landing#32]
[ETHSofia Logo.zip](https://github.com/node101-io/landing/files/15388159/ETHSofia.Logo.zip)

Don't miss the opportunity to listen to more than forty speakers from the leading companies of the blockchain ecosystem, meet people from the ecosystem and hack award-filled hackathon tracks in ETH Sofia, which will be held in Sofia on 17-19 October 2024, where node101 is the developer community partner.

Don't forget to take advantage of the discount given to Turkish software developers.

**Comment by gergineth** [comment]
https://www.ethsofia.com/

bu adresi de linkleriz

**Comment by atahanyild** [comment]
irrelevant
